// Auto-generated by scripts/optimize-images.mjs - DO NOT EDIT
export interface ImageSize {
  path: string;
  width: number;
  height: number;
}

export interface ImageEntry {
  slug: string;
  category: string;
  alt: string;
  tags: string[];
  originalWidth: number;
  originalHeight: number;
  blurDataURI: string;
  sizes: Record<number, ImageSize>;
}

export const images: Record<string, ImageEntry> = {
  'creation-6': {
    slug: 'creation-6',
    category: 'creation',
    alt: 'Allee paysagere en gravier dans un parc arbore - paysagiste Angers',
    tags: ['creation', 'allee', 'gravier', 'parc'],
    originalWidth: 4284,
    originalHeight: 5712,
    blurDataURI: 'data:image/webp;base64,UklGRnAAAABXRUJQVlA4IGQAAADwAwCdASoUABQAPzmKulWvKSWjKA1R4CcJQBbZAfj+R+46c71sIeEAAP5JhqyIgV4loNmfM+90iPbuxr4c6rhMSciclminy2ZcZ/FptTkqvu95gyTQKtP+eW4016fT9jBtgAAA',
    sizes: {
    480: { path: '/images/realisations/creation-6-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/creation-6-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/creation-6-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/creation-6-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'entretien-2': {
    slug: 'entretien-2',
    category: 'entretien',
    alt: 'Jardin paysager avec piscine et topiaires parfaitement entretenus',
    tags: ['entretien', 'piscine', 'topiaires', 'jardin'],
    originalWidth: 2208,
    originalHeight: 1656,
    blurDataURI: 'data:image/webp;base64,UklGRp4AAABXRUJQVlA4IJIAAADQBACdASoUABQAPzmUwFmvKiajqAgB4CcJQBbZAiM9JN84XVp7nTrrJWlVR2gIAAD+ZZacilhSe6Xpe8Y4Nf2moLKZtvdknrnNkd7QaZ7jzxYoMHWDauRqGl2VwJNH1vJmoezruDl/NV2HlXvgF0ARzGAiwpCeh99FdpuA8JuNEVfgLHRn9Tde3nnaujZvvYAAAA==',
    sizes: {
    480: { path: '/images/realisations/entretien-2-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/entretien-2-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/entretien-2-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/entretien-2-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-7': {
    slug: 'creation-7',
    category: 'creation',
    alt: 'Terrasse en gravier stabilise avec muret en acier corten et massifs fleuris - paysagiste Angers',
    tags: ['creation', 'terrasse', 'corten', 'massifs'],
    originalWidth: 5712,
    originalHeight: 4284,
    blurDataURI: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAABwBACdASoUABQAPzmUwVmvKicjqAgB4CcJYwDA3AVTnshDa/IsAX2fFy+MgAD5NFqINHmn7iuloniXPPp+ZyHSVr81EsLoCfCvvn2b+JSiiS7nZaPb+n7nOFuqhf57qBhawklYaUKiVy7fG4bZMOkwAcErCvBv3MwJP4AA',
    sizes: {
    480: { path: '/images/realisations/creation-7-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-7-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-7-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-7-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'elagage-2': {
    slug: 'elagage-2',
    category: 'elagage',
    alt: 'Elagueur professionnel en action dans un arbre a Angers',
    tags: ['elagage', 'professionnel', 'intervention'],
    originalWidth: 1200,
    originalHeight: 1600,
    blurDataURI: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAADQBACdASoUABQAPzmOuVavKaUjqA1R4CcJYgC90BF+2bx5pJzSINDcJaq1XtqdcAD+dYqTV+yHIvYrkhfNiG6jIilmMWDbvyaFYIQiX2FdLE0QodJt77fuUTgD2QUMYzDy9Xpvmki/OLMcmcE7qCQQp7Y6HAa3OmAAAA==',
    sizes: {
    480: { path: '/images/realisations/elagage-2-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/elagage-2-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/elagage-2-1200w.webp', width: 1200, height: 1600 }
    },
  },
  'terrasse-2': {
    slug: 'terrasse-2',
    category: 'terrasse',
    alt: 'Terrasse en pierre naturelle avec amenagement paysager complet',
    tags: ['terrasse', 'pierre', 'amenagement'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRowAAABXRUJQVlA4IIAAAACQBACdASoUABQAPzmUwFmvKiajqAgB4CcJZwDCgAzquIOF84TZCkTxfMikwgAAzfkki1zconyY9AJM/0Wf2ttGAstzIz3Li1LUBLjX5Mr/VEbAiYSHIKWZsDuMNiIlSgmDK4/gM6Rq3vF8MB+RvRgGsk0VOVHa81oVoMN9slgAAA==',
    sizes: {
    480: { path: '/images/realisations/terrasse-2-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/terrasse-2-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/terrasse-2-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/terrasse-2-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-4': {
    slug: 'creation-4',
    category: 'creation',
    alt: 'Escalier en ardoise et pas japonais avec paillage bois - amenagement jardin Angers',
    tags: ['creation', 'escalier', 'ardoise', 'pas-japonais'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAABwBACdASoUABQAPzmMuVavKSUjqA1R4CcJYwC4MAzjXjw9ohestMpms0TGwAD6iVOxJzu3USbRC0hpb8+biKGgkveFqwj7ioOtVIv0JWg11GH1Tp8E+pTY9XRDhMxnwZYWyK5m5VWYib3/bHLS/UD9UcQuVVpNZMKb8HlEj4HTv+SHBj1QMKptMAA=',
    sizes: {
    480: { path: '/images/realisations/creation-4-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-4-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-4-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-4-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'cloture-1': {
    slug: 'cloture-1',
    category: 'cloture',
    alt: 'Pose de cloture en bois pour delimitation de jardin pres d\'Angers',
    tags: ['cloture', 'bois', 'delimitation'],
    originalWidth: 5712,
    originalHeight: 4284,
    blurDataURI: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAADwAwCdASoUABQAPzmMulYvKSWkqA1R4CcJQBibAQMFH2ah49nGg3sAAOF/X8O4AABNYIiYB3j3A0FpV+3/zQqJkPphYnIJ7Jx90w2u1CGjXV0/I6IyCFpyjHI7IAAA',
    sizes: {
    480: { path: '/images/realisations/cloture-1-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/cloture-1-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/cloture-1-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/cloture-1-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'arrosage-1': {
    slug: 'arrosage-1',
    category: 'arrosage',
    alt: 'Systeme d\'arrosage automatique installe dans un jardin paysager a Angers',
    tags: ['arrosage', 'automatique', 'jardin'],
    originalWidth: 3840,
    originalHeight: 2160,
    blurDataURI: 'data:image/webp;base64,UklGRmoAAABXRUJQVlA4IF4AAABQBACdASoUABQAPzmUwFovKaakKAgB4CcJQBkTAeyR4hfrOEAQe6aIMx5oAPi9y9cklCz+ryePjhqHHlYym5HMExFkB98XWuVwgJKRseuzrg+6XkhuE1R+wgzM+AAA',
    sizes: {
    480: { path: '/images/realisations/arrosage-1-480w.webp', width: 480, height: 270 },
    800: { path: '/images/realisations/arrosage-1-800w.webp', width: 800, height: 450 },
    1200: { path: '/images/realisations/arrosage-1-1200w.webp', width: 1200, height: 675 },
    1920: { path: '/images/realisations/arrosage-1-1920w.webp', width: 1920, height: 1080 }
    },
  },
  'creation-9': {
    slug: 'creation-9',
    category: 'creation',
    alt: 'Parc paysager amenage avec allee en gravier et espace reception - creation paysagere Angers',
    tags: ['creation', 'parc', 'allee', 'reception'],
    originalWidth: 5712,
    originalHeight: 4284,
    blurDataURI: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAACQBACdASoUABQAPzmUwVmvKicjqAgB4CcJZADE2Ap3Y0sz67zKkXDlkUm8UdQA/bOZ+XfFM9a+vtiJek+dfHXNU9u/UMK3IV03FXdp0TqEegTelfiGyZkYpBpblWYQ3ErQJFBaGelSHm13Go4x/eg2w957QPRWQZBxnywAAAA=',
    sizes: {
    480: { path: '/images/realisations/creation-9-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-9-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-9-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-9-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-8': {
    slug: 'creation-8',
    category: 'creation',
    alt: 'Muret en acier corten avec escalier et plantations paysageres pres d\'Angers',
    tags: ['creation', 'corten', 'escalier', 'plantations'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRpgAAABXRUJQVlA4IIwAAABwBACdASoUABQAPzmQvVgvKaYjqAqp4CcJYgCw7A3R0Q21bZpWhnIm7SkIAAD2JZ7MQACzb0upIB/EMtkOp4gRko6OAHXu84m8/zIWeRwxp3NMjJBC/7IR5Z8y2ycKb5L4+Yrp/ZF/F+41tnqJU/XgRJelDFonw33qoNPE2m533oV8iTvBYmxFwAAAAA==',
    sizes: {
    480: { path: '/images/realisations/creation-8-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-8-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-8-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-8-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-5': {
    slug: 'creation-5',
    category: 'creation',
    alt: 'Pergola en bois et allee en pas japonais dans un jardin paysager a Angers',
    tags: ['creation', 'pergola', 'bois', 'allee'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRogAAABXRUJQVlA4IHwAAACQBACdASoUABQAPzmUwFmvKiajqAgB4CcJQBjIAW87GOQN8KWW2mSl1nkEqDAA9qrsQz7bOVgIy4QXoMl78/kBIVjLB/xFZ+ffeLmWzqKaLTSmv9tw7UFElO2ChEkk1DRTPJAYWaHLjiy14+COkrjJE3bgTtwaYdXS5oAA',
    sizes: {
    480: { path: '/images/realisations/creation-5-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-5-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-5-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-5-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-1': {
    slug: 'creation-1',
    category: 'creation',
    alt: 'Creation de massifs floraux et allee paysagere a Angers',
    tags: ['creation', 'massifs', 'allee'],
    originalWidth: 1472,
    originalHeight: 828,
    blurDataURI: 'data:image/webp;base64,UklGRpoAAABXRUJQVlA4II4AAADQBACdASoUABQAPzmSv1mvKaajqAgB4CcJQBhnNXgJWpSCBa0POy6EX6wIn1LoAAD+0Jz8LqgHFKkphpaWahTiTm0J3deg68xyV44sP8WesUCLjw7arpHHp7gJfja1M4zTia2ub39+R4CUmo7mQW58ANzjXoF6zmEADaSCPLDA2kRNd3bmaC22QI7ccAAA',
    sizes: {
    480: { path: '/images/realisations/creation-1-480w.webp', width: 480, height: 270 },
    800: { path: '/images/realisations/creation-1-800w.webp', width: 800, height: 450 },
    1200: { path: '/images/realisations/creation-1-1200w.webp', width: 1200, height: 675 }
    },
  },
  'creation-2': {
    slug: 'creation-2',
    category: 'creation',
    alt: 'Amenagement paysager complet avec allee en gravillon et massifs vegetaux',
    tags: ['creation', 'allee', 'gravillon', 'massifs'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRnQAAABXRUJQVlA4IGgAAAAQBACdASoUABQAPzmOwFevKacjqAqp4CcJYwC7AAucvid4mv7fFXaDQAD8jt0dtw4quzCmDCrAPtYfGAz0PUlFOazO1prRTc1e1HygitWZreeSE5BHNykM35nQ1uIlDP9zsEZKSQgAAA==',
    sizes: {
    480: { path: '/images/realisations/creation-2-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-2-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-2-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-2-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-3': {
    slug: 'creation-3',
    category: 'creation',
    alt: 'Realisation d\'un jardin contemporain avec plantations variees',
    tags: ['creation', 'contemporain', 'plantations'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQBACdASoUABQAPzmUwFmvKiajqAgB4CcJQBibAYum36YRZsdS+lcDIQWRkTbBAAD9jUc4rXk6y9ghC2IuvcbKyGOT1Ek1ZT3fWhvS0u4DuaeBIp6otq55tT8nteDXVW5KgMn8auzIl//E+KHcpoAsAAWyQAjjMAA=',
    sizes: {
    480: { path: '/images/realisations/creation-3-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-3-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-3-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-3-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'entretien-1': {
    slug: 'entretien-1',
    category: 'entretien',
    alt: 'Haie taillee impeccablement par les jardiniers d\'Art des Jardins',
    tags: ['entretien', 'haie', 'taille'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRo4AAABXRUJQVlA4IIIAAACwBACdASoUABQAPzmGvVQvKSajKA1R4CcJagCxFIAAoHUBQfbTjsmQK9/dESwAAP3btK9xw7WfwoufFka0d9zlmCi6pCJI7kOxLBC2TsjWfcXPeI4aE6cn1doAUJM2AOqNh9YdntuyHlqoC6SKJV2FY0L1pEqyeFcL9MjlIb66fwAA',
    sizes: {
    480: { path: '/images/realisations/entretien-1-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/entretien-1-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/entretien-1-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/entretien-1-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'entretien-3': {
    slug: 'entretien-3',
    category: 'entretien',
    alt: 'Pelouse parfaitement entretenue au coucher de soleil - entretien jardin Angers',
    tags: ['entretien', 'pelouse', 'coucher-soleil'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRnIAAABXRUJQVlA4IGYAAAAQBACdASoUABQAPzmKu1WvKS0jKA1R4CcJYgCdMt8Bl+6y7wALGOllAADJXHoplweOUMqXIgZWu0MHEUM3lwNIiZrX2mK0FOIzjPC/aHoKrnp7pecHnr0kItxdJ1vPUJOaBDUwAAA=',
    sizes: {
    480: { path: '/images/realisations/entretien-3-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/entretien-3-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/entretien-3-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/entretien-3-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'elagage-1': {
    slug: 'elagage-1',
    category: 'elagage',
    alt: 'Grands arbres vus en contre-plongee avant intervention d\'elagage',
    tags: ['elagage', 'grands-arbres', 'hauteur'],
    originalWidth: 3024,
    originalHeight: 4032,
    blurDataURI: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAADQAwCdASoUABQAPzmUwVmvKicjqAgB4CcJZwAAC5Awau7D7PsuB0AA/i5NSWCA4bTjsKSXt2tis8wLY11QxS6zk0erU4Xgm74y6GVEydzt25UiOzMCXOluW9NTVCwtK/oPiauyXCs8kZAoxyTpQ5FR2VccMr+eIAA=',
    sizes: {
    480: { path: '/images/realisations/elagage-1-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/elagage-1-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/elagage-1-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/elagage-1-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'elagage-3': {
    slug: 'elagage-3',
    category: 'elagage',
    alt: 'Resultat de taille d\'arbres soignee par Art des Jardins',
    tags: ['elagage', 'taille', 'resultat'],
    originalWidth: 3024,
    originalHeight: 4032,
    blurDataURI: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAABwBQCdASoUABQAPzmOuVavKaUjqA1R4CcJYgCdM4CBWzpZiXrhx8rPp+TLMaD5EkV2vXMAANq86kKdoP1gH4ao+XlLRCiSzpg8olDxYFNWi4/FBIxtxyJWhljfc5mdzh7GnifFS/RXEDkKBOStYToVG8QCNKD4gWsgAA==',
    sizes: {
    480: { path: '/images/realisations/elagage-3-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/elagage-3-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/elagage-3-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/elagage-3-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'elagage-4': {
    slug: 'elagage-4',
    category: 'elagage',
    alt: 'Taille de formation sur arbre ornemental dans le Maine-et-Loire',
    tags: ['elagage', 'formation', 'ornemental'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRnYAAABXRUJQVlA4IGoAAACwBACdASoUABQAPzmUwFmvKiajqAgB4CcJZQC/7AvwKh6DP4j0ZKXAKYh+0f2AAPRF+qxS49YLHUDcYXEUbQ78KLHKM70JWyfgc68Ax/VMILfFSAKbTtvCohH/+MgEVvf+QiO3UBGwAAAA',
    sizes: {
    480: { path: '/images/realisations/elagage-4-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/elagage-4-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/elagage-4-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/elagage-4-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'elagage-5': {
    slug: 'elagage-5',
    category: 'elagage',
    alt: 'Elagage de securisation sur un arbre mature pres d\'habitation',
    tags: ['elagage', 'securisation', 'arbre-mature'],
    originalWidth: 3024,
    originalHeight: 4032,
    blurDataURI: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAADwBACdASoUABQAPzmUwFmvKaajqAgB4CcJZQDN/BDVPNABs7c3RwC3DoWIB6kCiIAA/p1YXNIwHCA8xOCNAnM4bczRtFYmYouXsh+QGjkOatvtmcRBnbJCM3Mq3f81SYQVSVa+hzDl/wdq+iXbAAetYuHJkRJT9pDaufDLRi1scBD6Ht07k2mE+jONGTE3AAA=',
    sizes: {
    480: { path: '/images/realisations/elagage-5-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/elagage-5-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/elagage-5-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/elagage-5-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'terrasse-3': {
    slug: 'terrasse-3',
    category: 'terrasse',
    alt: 'Creation de terrasse et espace de vie exterieur a Angers',
    tags: ['terrasse', 'espace-vie', 'exterieur'],
    originalWidth: 3024,
    originalHeight: 4032,
    blurDataURI: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACwBACdASoUABQAPzmSu1gvKiWjqAqp4CcJQBajdDgpFXepSCBHjxMlU9xYXjgAAP4Zw/Y3Je59k0m/rePaJQCm/hvkT+oZFlA3O53mJV7/yij3lHvc1Ig7hobrLrJjMOYTc6XLww8P/4NJQ+QMNnq6mzXo8j0/AAA=',
    sizes: {
    480: { path: '/images/realisations/terrasse-3-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/terrasse-3-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/terrasse-3-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/terrasse-3-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'terrasse-1': {
    slug: 'terrasse-1',
    category: 'terrasse',
    alt: 'Terrasse en bois composite amenagee dans un jardin paysager',
    tags: ['terrasse', 'bois', 'composite'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRpYAAABXRUJQVlA4IIoAAAAQBQCdASoUABQAPzmUwFmvKiajqAgB4CcJZgCdMtDBKZlAM3C8g8kIAHBBYfPOfCqAAP7WxglMHaafqcpkTUpQsjy9pZ+CZcTgY25hYQmNJ/8/wkeQYMLxBLvQUbzcjvze6QCr0uocsJSAuoDoacXpbxmarfuCg0IBF4PBpET4Vz12cCMgihegAAA=',
    sizes: {
    480: { path: '/images/realisations/terrasse-1-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/terrasse-1-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/terrasse-1-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/terrasse-1-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'cloture-2': {
    slug: 'cloture-2',
    category: 'cloture',
    alt: 'Cloture decorative en panneaux rigides installee par Art des Jardins',
    tags: ['cloture', 'panneaux', 'rigides'],
    originalWidth: 5712,
    originalHeight: 4284,
    blurDataURI: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBQCdASoUABQAPzmUwFmvKiajqAgB4CcJYgDE2A8w7UFx1CfIdhTo8O5aqk5lnBoAAP65NXOQ+kkqtRsqt13jDgqqQW4zqoitprPesk74ZIWwPhqkpG2TPYbCefl8doPJFBuagNFJ4ajUORS2wwGF2Rab2gAA',
    sizes: {
    480: { path: '/images/realisations/cloture-2-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/cloture-2-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/cloture-2-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/cloture-2-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'cloture-3': {
    slug: 'cloture-3',
    category: 'cloture',
    alt: 'Amenagement de cloture et portillon pour entree de propriete',
    tags: ['cloture', 'portillon', 'entree'],
    originalWidth: 4284,
    originalHeight: 5712,
    blurDataURI: 'data:image/webp;base64,UklGRnwAAABXRUJQVlA4IHAAAADwAwCdASoUABQAPzmUwVmvKicjqAgB4CcJZQDHMAim9q03jsSaf/kAAOJDP1jqJchu/nZD3jgaYNoqX/avrrvTtz/61TF4FJ9T8UXm0AqopB248/gFQ92YSLPqjz/gzwOcrECiOs0J+KgRZ+A4mAAA',
    sizes: {
    480: { path: '/images/realisations/cloture-3-480w.webp', width: 480, height: 640 },
    800: { path: '/images/realisations/cloture-3-800w.webp', width: 800, height: 1067 },
    1200: { path: '/images/realisations/cloture-3-1200w.webp', width: 1200, height: 1600 },
    1920: { path: '/images/realisations/cloture-3-1920w.webp', width: 1920, height: 2560 }
    },
  },
  'cloture-4': {
    slug: 'cloture-4',
    category: 'cloture',
    alt: 'Installation de cloture composite moderne dans le Maine-et-Loire',
    tags: ['cloture', 'composite', 'moderne'],
    originalWidth: 5712,
    originalHeight: 4284,
    blurDataURI: 'data:image/webp;base64,UklGRn4AAABXRUJQVlA4IHIAAADwAwCdASoUABQAPzmKulWvKSWjKA1R4CcJYwC/OAsk9Erv5GvMrgEAAP61m9EiWmRve7k7GidR26DO4ArjY9Yo+aRftGgTIDCq6rAvcvtkU0QSfwmXUagZ+FM8pK8zxlc7uFMnRJdLG85l30pbZpVoAAA=',
    sizes: {
    480: { path: '/images/realisations/cloture-4-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/cloture-4-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/cloture-4-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/cloture-4-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'chantier-avant-1': {
    slug: 'chantier-avant-1',
    category: 'entretien',
    alt: 'Jardin envahi par la vegetation avant intervention de debroussaillage a Angers',
    tags: ['entretien', 'debroussaillage', 'avant'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRoYAAABXRUJQVlA4IHoAAACwBACdASoUABQAPzmQuVivKaUjqAqp4CcJYgCsM1XBXLsG6RKZnh7Wl/1tRNucAP5UBlK2vuy/PXlLjSK0JKgmBEq2Xix5KNxX+TQZ337TDM9mtwKMOAfXGpgT9waIFac+TVISWCRXnTTHDC/GC8LFA5qzZoaFpIYKAA==',
    sizes: {
    480: { path: '/images/realisations/chantier-avant-1-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/chantier-avant-1-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/chantier-avant-1-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/chantier-avant-1-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'chantier-apres-1': {
    slug: 'chantier-apres-1',
    category: 'entretien',
    alt: 'Jardin defriche et remis au propre apres debroussaillage par Art des Jardins',
    tags: ['entretien', 'debroussaillage', 'apres'],
    originalWidth: 4032,
    originalHeight: 3024,
    blurDataURI: 'data:image/webp;base64,UklGRnoAAABXRUJQVlA4IG4AAAAQBACdASoUABQAPzmOwFcvKacjqAqp4CcJYwDA3A+CT+9uoTYNGhpZxgD+cqbOazTuoYTdhpOyoErbokfCRpwEONF00cJqAYPR46vR6BbRHj4NDQLuflC2fGX/aEuzk+HGA8WVA/OIFjS50SAAAA==',
    sizes: {
    480: { path: '/images/realisations/chantier-apres-1-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/chantier-apres-1-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/chantier-apres-1-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/chantier-apres-1-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-8-avant': {
    slug: 'creation-8-avant',
    category: 'creation',
    alt: 'Parc non amenage avec pelouse brute avant creation paysagere a Angers',
    tags: ['creation', 'avant', 'parc'],
    originalWidth: 1903,
    originalHeight: 1476,
    blurDataURI: 'data:image/webp;base64,UklGRoQAAABXRUJQVlA4IHgAAACQBACdASoUABQAPzmKu1UvKSYjKA1R4CcJagC06A2eLjfdit0YSXbA/e+syJgA9wbZq5TX6Xnx1cEz4xBJcVpCkCEL7hzc76kFs8DB/NkQTr7ZVmkWPbA2oPfH/YhO2PexcS9m4TqEWBYwkdYQdX1CEHZ+K2XgAAA=',
    sizes: {
    480: { path: '/images/realisations/creation-8-avant-480w.webp', width: 480, height: 372 },
    800: { path: '/images/realisations/creation-8-avant-800w.webp', width: 800, height: 620 },
    1200: { path: '/images/realisations/creation-8-avant-1200w.webp', width: 1200, height: 931 },
    1920: { path: '/images/realisations/creation-8-avant-1920w.webp', width: 1903, height: 1476 }
    },
  },
  'creation-10-avant': {
    slug: 'creation-10-avant',
    category: 'creation',
    alt: 'Jardin en friche avec vegetation desordonnee avant amenagement paysager',
    tags: ['creation', 'avant', 'friche'],
    originalWidth: 2048,
    originalHeight: 1536,
    blurDataURI: 'data:image/webp;base64,UklGRooAAABXRUJQVlA4IH4AAAAQBQCdASoUABQAPzmUwVmvKicjqAgB4CcJQBdgAiaV/WdzoIUeeeIIm5UbU27otUqAAP7TF3lsZKEwOPQMl6kSjrmEcEkGJtUdjmhDfUZbuRfT2VGGxA2jkxojt8DoMxHqme1YYskpMOt3b1p3c0XfqvQPNLjaimjbYAywAAA=',
    sizes: {
    480: { path: '/images/realisations/creation-10-avant-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-10-avant-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-10-avant-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-10-avant-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'creation-10': {
    slug: 'creation-10',
    category: 'creation',
    alt: 'Jardin amenage avec allee en paves et massifs vegetaux apres creation paysagere',
    tags: ['creation', 'allee', 'paves', 'massifs'],
    originalWidth: 2048,
    originalHeight: 1536,
    blurDataURI: 'data:image/webp;base64,UklGRpwAAABXRUJQVlA4IJAAAABwBQCdASoUABQAPzmUwVmvKicjqAgB4CcJQBibAhy/837kJ6CqkVqoCPEsJZhUA5isLq4AAP7TOMOkEtUn8voUyTFd7CwLoCi0WDmvMoyMGvrMVhEdmbvf/eI/a7XYeveR0Jm4G5OUTHeKhlShnG3HFP8twFSyt6SVAkTXNGLmLCgLvwZ4YgZMMzgJVWSAAAA=',
    sizes: {
    480: { path: '/images/realisations/creation-10-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/creation-10-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/creation-10-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/creation-10-1920w.webp', width: 1920, height: 1440 }
    },
  },
  'terrasse-1-avant': {
    slug: 'terrasse-1-avant',
    category: 'terrasse',
    alt: 'Spa pose sur herbe sans amenagement avant construction terrasse bois',
    tags: ['terrasse', 'avant', 'spa'],
    originalWidth: 2048,
    originalHeight: 1536,
    blurDataURI: 'data:image/webp;base64,UklGRoIAAABXRUJQVlA4IHYAAAAQBACdASoUABQAPzmQvFgvKaWjqAqp4CcJQBdgAaE809sa7F8FivVm4AD+3ugTO39tdo2pQg/frtpvLFXLG7UAOsP9BGSjk0XEK+LQj8DK0CiJG7JdKmBDB3mXzVZQjlAvY+L+w2pqGkRq3AIFraaB/yAcdAAA',
    sizes: {
    480: { path: '/images/realisations/terrasse-1-avant-480w.webp', width: 480, height: 360 },
    800: { path: '/images/realisations/terrasse-1-avant-800w.webp', width: 800, height: 600 },
    1200: { path: '/images/realisations/terrasse-1-avant-1200w.webp', width: 1200, height: 900 },
    1920: { path: '/images/realisations/terrasse-1-avant-1920w.webp', width: 1920, height: 1440 }
    },
  }
};

export const categories = ['creation', 'elagage', 'entretien', 'terrasse', 'cloture', 'arrosage'] as const;
export type ImageCategory = typeof categories[number];

export function getImagesByCategory(category: ImageCategory): ImageEntry[] {
  return Object.values(images).filter((img) => img.category === category);
}

export function getImage(slug: string): ImageEntry | undefined {
  return images[slug];
}

export function getSrcSet(entry: ImageEntry): string {
  return Object.entries(entry.sizes)
    .map(([, size]) => `${size.path} ${size.width}w`)
    .join(', ');
}

export function getDefaultSrc(entry: ImageEntry, preferredWidth = 800): string {
  const widths = Object.keys(entry.sizes).map(Number).sort((a, b) => a - b);
  const closest = widths.reduce((prev, curr) =>
    Math.abs(curr - preferredWidth) < Math.abs(prev - preferredWidth) ? curr : prev
  );
  return entry.sizes[closest].path;
}

// Hero image mappings per page
export const heroImages = {
  homepage: 'entretien-2',
  'paysagiste-angers': 'creation-9',
  'elagage-angers': 'elagage-3',
  'entretien-jardin-angers': 'entretien-3',
  'abattage-angers': 'elagage-1',
  contact: 'terrasse-2',
} as const;

// Service card image mappings
export const serviceCardImages = {
  paysagisme: 'creation-9',
  'entretien-jardin': 'entretien-3',
  elagage: 'elagage-2',
  abattage: 'elagage-1',
  terrasse: 'terrasse-2',
  cloture: 'cloture-1',
  'taille-haies': 'entretien-1',
  debroussaillage: 'chantier-avant-1',
  'arrosage-automatique': 'arrosage-1',
} as const;

// Service hero mappings for dynamic [serviceCity] pages
export const serviceHeroImages: Record<string, string> = {
  paysagiste: 'creation-9',
  'entretien-jardin': 'entretien-3',
  elagage: 'elagage-3',
  abattage: 'elagage-1',
  terrasse: 'terrasse-2',
  cloture: 'cloture-1',
  'taille-haies': 'entretien-1',
  debroussaillage: 'chantier-avant-1',
  'arrosage-automatique': 'arrosage-1',
};

// OG image paths per service
export const ogImages = {
  default: '/images/og-image.jpg',
  paysagisme: '/images/og-paysagisme.jpg',
  elagage: '/images/og-elagage.jpg',
  entretien: '/images/og-entretien.jpg',
  abattage: '/images/og-abattage.jpg',
} as const;
